sample:
  id:
    translation: id
    blank_policy: error
  nome:
    translation: name
  idade:
    translation: age
    blank_polity: warn #default value
    convert: integer
  diagnostico: 
    translation: diagnosis
    blank_policy: ignore
